name: Package Addon

on:
  push:
    branches: [ master ]
    tags: [ "*" ]

# Permission can be added at job level or workflow level
permissions:
  contents: write   # This is required to create/push the new git tag

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Clone project
        uses: actions/checkout@v4

      - name: Package and release Retail
        uses: BigWigsMods/packager@master

      - name: Package and release Wrath
        uses: BigWigsMods/packager@master
        with:
          args: -g wrath

      - name: Package and release Classic
        uses: BigWigsMods/packager@master
        with:
          args: -g classic

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          files: .release/Outfitter-${{env.RELEASE_TAG}}*.zip
          tag_name: ${{ env.RELEASE_TAG }}
          #release_name: ${{ env.RELEASE_TAG }}
          draft: false
          prerelease: true